import "./base.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import clsx from "clsx";
import type { Metadata } from "next";
import { Fira_Code, Noto_Sans_SC, Open_Sans } from "next/font/google";
import { PropsWithChildren } from "react";
import "./app.css";
import NavigationSidebar from "./navigation";

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-noto-sans-sc",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans",
});

const firaCode = Fira_Code({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-fira-code",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html
      lang="zh-CN"
      suppressHydrationWarning
      className={clsx(
        openSans.variable,
        notoSansSC.variable,
        firaCode.variable,
      )}
    >
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <NavigationSidebar />
            <main className="flex-1 overflow-auto">
              <header className="flex px-3 py-2">
                <SidebarTrigger variant="outline" />
              </header>
              {children}
            </main>
            <Toaster />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;
